name: Deploy to Server

on:
#  push:
#    branches:
#      - main  # Trigger on push to main branch
  pull_request:
    branches:
      - '*'

jobs:
  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest

    environment: main

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SSH Client
        run: sudo apt-get install -y openssh-client

      - name: Copy SSH Key
        run: echo "$SSH_PRIVATE_KEY" > id_ed25519
      - name: Set Key Permissions
        run: chmod 600 id_ed25519

      # - name: Add SSH Key and Known Hosts
      #   run: |
      #     eval $(ssh-agent -s)
      #     ssh-add -t 60 id_ed25519  # Add ed25519 key with 60s timeout
      #     ssh-keyscan -t ed25519 -H $SERVER_HOST >> ~/.ssh/known_hosts

      - name: Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no -i id_ed25519 $SSH_USER@$SERVER_HOST << EOF
            cd /var/opt/docker/eco-challenger/eco-challenger
            git pull origin main
            
            cd /var/opt/docker/eco-challenger
            docker compose down
            docker compose build --no-cache
            docker compose up -d
          EOF

      - name: Cleanup SSH Key
        run: rm id_ed25519
