name: Lint Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  frontend:
    name: Build and run linter for frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 23.9.0

      - name: Install dependencies
        run: cd ClientApp && npm install

      - name: Run lint
        run: cd ClientApp && npm run lint

      - name: Build Angular App
        run: cd ClientApp && npm run build --prod

  build:
    name: Build backend
    runs-on: ubuntu-latest
    needs: frontend  # Run this only if frontend job succeeds

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      # Build .NET Core Backend
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.0

      - name: Restore .NET Core dependencies
        run: dotnet restore EcoChallenger/EcoChallenger.csproj

      - name: Build .NET Core Backend
        run: dotnet publish EcoChallenger/EcoChallenger.csproj -c Release -o /app/publish

      # Verify Build Artifacts
      - name: List Angular Build Artifacts
        run: ls -la ClientApp/dist/client-app/browser

      - name: List .NET Core Build Artifacts
        run: ls -la /app/publish
