name: Lint Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  lint:
    name: Run linter for client side
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.9.0
          cache: 'pnpm'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: cd ClientApp && pnpm install

      - name: Run lint
        run: cd ClientApp && pnpm lint
